# Generated by Django 4.0.8 on 2022-12-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbag',
            name='end_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userbag',
            name='start_at',
            field=models.DateTimeField(null=True),
        ),
    ]
