# Generated by Django 4.0.8 on 2022-12-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_interchangeable_alter_inventorytarif_default_and_more'),
        ('product', '0002_userbag_end_at_userbag_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parts',
            field=models.ManyToManyField(to='manager.interchangeable'),
        ),
    ]
