# Generated by Django 4.0.8 on 2022-12-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_interchangeable_alter_inventorytarif_default_and_more'),
        ('product', '0003_product_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parts',
            field=models.ManyToManyField(related_name='products', to='manager.interchangeable'),
        ),
    ]
