# Generated by Django 4.0.8 on 2023-01-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_orderrequestinventory_product'),
        ('product', '0005_remove_product_parts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='manager.interchangeable')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
