# Generated by Django 4.1.1 on 2022-10-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_activet_product_parent_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='activet',
            new_name='active',
        ),
    ]
