# Generated by Django 4.1.1 on 2022-10-03 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_activet_product_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parent_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_products', to='product.product'),
        ),
    ]
