# Generated by Django 4.1.1 on 2022-10-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productphoto',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'carousel'), (1, 'preview')], default=0),
        ),
    ]
