# Generated by Django 4.1.1 on 2022-10-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productphoto_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='set_products',
            field=models.ManyToManyField(blank=True, null=True, related_name='set_products', to='product.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'товар'), (1, 'сет товаров')], default=0),
        ),
    ]
