# Generated by Django 4.1.1 on 2022-10-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_set_products_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_products', to='product.product'),
        ),
    ]
