# Generated by Django 4.1.1 on 2022-10-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_related_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='articule',
            field=models.CharField(default='asd', max_length=255),
        ),
    ]
