# Generated by Django 4.0.8 on 2022-10-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_entity_attribute_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='value',
            unique_together={('attribute', 'product')},
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute_kk',
            field=models.CharField(default='attribute_kk', max_length=255),
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute_ru',
            field=models.CharField(default='attribute_ru', max_length=255),
        ),
        migrations.AddField(
            model_name='value',
            name='value_kk',
            field=models.CharField(default='value_kk', max_length=255),
        ),
        migrations.AddField(
            model_name='value',
            name='value_ru',
            field=models.CharField(default='value_ru', max_length=255),
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='value',
            name='value',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
