# Generated by Django 4.0.8 on 2022-10-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_order_ord_id_product_instruction_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(default=5, verbose_name='Количество продукции'),
        ),
    ]
