# Generated by Django 4.0.8 on 2022-10-13 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.userbag'),
        ),
        migrations.AddField(
            model_name='order',
            name='first_time_order',
            field=models.BooleanField(default=False, verbose_name='Заказ первый раз'),
        ),
    ]
