# Generated by Django 4.0.8 on 2022-10-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_userbag_previous_order_delete_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Аттрибут', 'verbose_name_plural': 'Аттрибуты'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='userbag',
            options={'ordering': ['-created_at'], 'verbose_name': 'Корзина пользователя', 'verbose_name_plural': 'Корзина пользователей'},
        ),
        migrations.AlterField(
            model_name='order',
            name='total_discount_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Цена (co скидкой)'),
        ),
    ]
