# Generated by Django 4.0.8 on 2022-10-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_order_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
