# Generated by Django 4.0.8 on 2022-10-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_botuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
