# Generated by Django 4.0.8 on 2022-10-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_botuser_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
