# Generated by Django 4.0.8 on 2022-10-14 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_service_product_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('required', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.service')),
            ],
            options={
                'verbose_name': 'Товар (Сервис)',
                'verbose_name_plural': 'Товары (Сервис)',
                'ordering': ('created_at',),
            },
        ),
    ]
