# Generated by Django 4.0.8 on 2022-10-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_productservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='services',
        ),
    ]
