# Generated by Django 4.0.8 on 2022-10-14 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_remove_service_articule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productservice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='product.product'),
        ),
    ]
