# Generated by Django 4.0.8 on 2022-10-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_productphoto_service_alter_productphoto_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=36, verbose_name='Телефон'),
        ),
    ]
