# Generated by Django 4.0.8 on 2022-10-20 08:06

from django.db import migrations, models
import product.models.product_photo


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_alter_productphoto_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='image_thumb360',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=product.models.product_photo.thumb_dir, verbose_name='Фото (360px)'),
        ),
    ]
