# Generated by Django 4.0.8 on 2022-10-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_alter_productphoto_image_thumb360'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'товар'), (1, 'сет товаров'), (2, 'комплект')], default=0),
        ),
    ]
