# Generated by Django 4.0.8 on 2022-10-23 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_alter_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set', to='product.product')),
                ('set_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_objects', to='product.product')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('created_at',),
            },
        ),
    ]
