# Generated by Django 4.0.8 on 2022-10-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_productset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productset',
            options={'ordering': ('created_at',), 'verbose_name': 'Сет продукт', 'verbose_name_plural': 'Сет продукт'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='set_products',
        ),
    ]
