# Generated by Django 4.0.8 on 2022-10-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_alter_productset_options_remove_product_set_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parent_product',
        ),
    ]
