# Generated by Django 4.0.8 on 2022-10-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_remove_product_parent_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productset',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
