# Generated by Django 4.0.8 on 2022-10-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_alter_product_options_product_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category', 'order', 'created_at'), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
