# Generated by Django 4.0.8 on 2022-10-30 08:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None),
        ),
    ]
