# Generated by Django 4.0.8 on 2022-10-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_product_related_products_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='related_products',
        ),
    ]
