# Generated by Django 4.0.8 on 2022-11-12 14:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_alter_botuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rnh_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None),
        ),
    ]
