# Generated by Django 4.0.8 on 2022-11-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0059_productannouncement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productannouncement',
            options={'ordering': ('order',), 'verbose_name': 'Новый продукт', 'verbose_name_plural': 'Новые продукты'},
        ),
    ]
