# Generated by Django 4.0.8 on 2022-11-21 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0061_remove_product_rnh_ids_product_rnh_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rnh_id',
        ),
    ]
