# Generated by Django 4.0.8 on 2022-11-21 17:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0062_remove_product_rnh_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(verbose_name='Начало Акции')),
                ('end_date', models.DateTimeField(verbose_name='Конец Акции')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'db_table': 'product_discount',
            },
        ),
        migrations.CreateModel(
            name='ProductItemDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('discount_percent', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_items', to='product.productdiscount')),
                ('products', models.ManyToManyField(related_name='discounts', to='product.product')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'db_table': 'product_discount_item',
            },
        ),
    ]
