# Generated by Django 4.0.8 on 2022-11-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0064_userbag_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес доставки'),
        ),
    ]
