# Generated by Django 4.0.8 on 2022-11-26 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_clientpassportindividual_client_and_more'),
        ('product', '0065_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='manager.client'),
        ),
    ]
