# Generated by Django 4.0.8 on 2022-11-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0066_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_return',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес возврата'),
        ),
        migrations.AddField(
            model_name='userbag',
            name='delivery_back',
            field=models.BooleanField(default=False),
        ),
    ]
