# Generated by Django 4.0.8 on 2022-11-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='end_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='start_at',
            field=models.DateTimeField(null=True),
        ),
    ]
