# Generated by Django 4.0.8 on 2022-11-06 06:51

from django.db import migrations, models
import manage.models.stats


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_alter_botuser_user_id'),
        ('manage', '0003_alter_statistics_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='orders',
            field=models.ManyToManyField(to='product.order'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='start_at',
            field=models.DateTimeField(default=manage.models.stats.now_minus_30, null=True),
        ),
    ]
