# Generated by Django 4.0.8 on 2022-11-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0005_productstatistics_remove_statistics_orders_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcountstatistics',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productstatistics',
            options={'managed': False},
        ),
    ]
