# Generated by Django 4.0.8 on 2022-11-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0006_alter_productcountstatistics_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistics',
            options={'managed': False},
        ),
    ]
