# Generated by Django 4.0.8 on 2022-11-10 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0007_alter_statistics_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentInHandOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_rental', models.BigIntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('file_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RentInHandInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('amount_rent_sum', models.BigIntegerField(null=True)),
                ('price', models.BigIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage.rentinhandorder')),
            ],
        ),
    ]
