# Generated by Django 4.0.8 on 2022-11-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0008_rentinhandorder_rentinhandinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentinhandorder',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='RentInHandInventory',
        ),
    ]
