# Generated by Django 4.0.8 on 2022-11-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0011_rentinhandinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentinhandinventory',
            name='price',
            field=models.CharField(max_length=5192),
        ),
    ]
