# Generated by Django 4.0.8 on 2022-11-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0012_alter_rentinhandinventory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentinhandorder',
            name='order_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
