# Generated by Django 4.0.8 on 2022-11-14 09:12

import ckeditor_uploader.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_kk', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('body_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('body_kk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('products', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None)),
            ],
            options={
                'verbose_name': 'Обявление',
                'verbose_name_plural': 'Обявления',
                'ordering': ('created_at',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
