# Generated by Django 4.0.8 on 2022-11-14 14:40

import article.models.article
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_title_kk_alter_article_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to=article.models.article.image_dir, verbose_name='Фото'),
        ),
    ]
