# Generated by Django 4.0.8 on 2022-11-16 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_image_alter_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='image_ru',
        ),
    ]
