# Generated by Django 4.0.8 on 2022-11-22 11:24

import article.models.grants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_outer_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('instagram_url', models.URLField()),
                ('portfolio_url', models.URLField()),
                ('description', models.TextField(max_length=5192)),
                ('file', models.ImageField(upload_to=article.models.grants.file_dir)),
                ('date', models.DateField()),
                ('comment', models.TextField(max_length=5192)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Грант',
                'verbose_name_plural': 'Гранты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('order', 'created_at'), 'verbose_name': 'Обявление', 'verbose_name_plural': 'Обявления'},
        ),
    ]
