# Generated by Django 4.0.8 on 2022-11-22 12:18

import article.models.grants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_grantform_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantform',
            name='file',
            field=models.FileField(upload_to=article.models.grants.file_dir),
        ),
    ]
