# Generated by Django 4.0.8 on 2022-11-23 18:11

import article.models.grants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_alter_grantform_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantform',
            name='file',
            field=models.FileField(null=True, upload_to=article.models.grants.file_dir),
        ),
    ]
