# Generated by Django 4.0.8 on 2022-11-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_alter_grantform_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantform',
            name='comment',
            field=models.TextField(max_length=5192, null=True),
        ),
    ]
