# Generated by Django 3.2 on 2022-07-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, max_length=8, null=True)),
                ('image', models.ImageField(blank=True, default='garysh.jpg', null=True, upload_to='profile', verbose_name='Фото')),
                ('country', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user_type', models.PositiveIntegerField(choices=[(0, 'Школьник'), (1, 'Студент'), (2, 'Работаю'), (3, 'Другое')], default=0)),
                ('edu_place', models.CharField(max_length=255, null=True)),
                ('last_login', models.DateTimeField(auto_now_add=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
