# Generated by Django 4.0.8 on 2022-12-15 10:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerContants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=512)),
                ('type', models.PositiveIntegerField(choices=[(0, 'Физическое лицо'), (1, 'Юридическое лицо')], default=0)),
                ('birth_date', models.DateField()),
                ('attraction_method', models.CharField(choices=[('instagram', 'instagram'), ('telegram', 'telegram'), ('facebook', 'facebook'), ('google', 'google'), ('other', 'other')], max_length=255)),
                ('comment', models.TextField(max_length=512, null=True)),
                ('avatar', models.ImageField(null=True, upload_to='')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(default='#000', max_length=9, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('comment', models.TextField(max_length=512, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=255)),
                ('unique_id', models.CharField(max_length=32, unique=True)),
                ('buy_price', models.PositiveIntegerField(null=True)),
                ('buy_date', models.DateField(null=True)),
                ('comment', models.TextField(max_length=1024, null=True)),
                ('rent_count', models.PositiveIntegerField(default=0)),
                ('rent_money_amount', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField(max_length=512, null=True)),
                ('prefix', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField(max_length=512, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Свободно'), (1, 'Зарезервировано'), (2, 'В аренде'), (3, 'Сломано')], default=0)),
                ('disable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('default', models.PositiveIntegerField(choices=[(0, 'Обычная'), (1, 'В сете')], default=1)),
                ('name', models.CharField(default='name', max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('inventory', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='manager.inventory')),
                ('product_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'unique_together': {('default', 'inventory', 'price')},
            },
        ),
        migrations.CreateModel(
            name='ManagerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Зарезервировано'), (1, 'Отменен'), (2, 'В аренде'), (3, 'Частично возвращен'), (4, 'Возвращен')], default=0)),
                ('total_price', models.PositiveIntegerField()),
                ('products_price', models.PositiveIntegerField()),
                ('services_price', models.PositiveIntegerField()),
                ('rent_start', models.DateTimeField(null=True)),
                ('rent_end', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.client')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RentalPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=255)),
                ('inventories', models.ManyToManyField(related_name='product_parts', to='manager.inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManagerOrderInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Оборудование зарезервировано'), (1, 'Оборудование в аренде'), (2, 'Оборудование принято'), (3, 'Оборудование сломано')], default=0)),
                ('price', models.PositiveIntegerField()),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_inventories', to='manager.inventory')),
                ('manager_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.managerorder')),
                ('tarif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_inventories', to='manager.inventorytarif')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventorySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='manager.inventory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('photo', models.ImageField(upload_to='inventory')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='manager.inventory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.inventorycategory'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='rent_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.rentalpoint'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.inventorystatus'),
        ),
        migrations.CreateModel(
            name='ClientPassportLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('iin', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)])),
                ('address', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('contacts', models.TextField(max_length=512)),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_passports', to='manager.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientPassportIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('iin', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)])),
                ('document_number', models.CharField(max_length=255)),
                ('issue', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('issue_date_end', models.DateField()),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_passports', to='manager.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('discount_percent', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99)])),
                ('discount_amount', models.PositiveIntegerField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='manager.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='tick',
            field=models.ManyToManyField(to='manager.clienttick'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
