# Generated by Django 4.0.8 on 2022-11-12 13:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerProductStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManagerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManagerRentInHandInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5192)),
                ('amount_rent_sum', models.BigIntegerField(null=True)),
                ('price', models.CharField(max_length=5192)),
            ],
            options={
                'db_table': 'rent_in_hand_inventories',
            },
        ),
        migrations.CreateModel(
            name='ManagerRentInHandOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField()),
                ('sum_rental', models.BigIntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('file_data', models.JSONField()),
                ('file', models.FileField(default=None, null=True, upload_to='')),
                ('inventories', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'rent_in_hand_orders',
            },
        ),
    ]
