# Generated by Django 4.0.8 on 2022-12-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_userbag_end_at_userbag_start_at'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='product.product'),
        ),
    ]
