# Generated by Django 4.0.8 on 2022-12-18 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_productpart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpassportindividual',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientpassportlegal',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='individual_passport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.clientpassportindividual'),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_passport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.clientpassportlegal'),
        ),
    ]
