# Generated by Django 4.0.8 on 2022-11-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_managerrentinhandinventory_rnh_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerrentinhandinventory',
            name='rnh_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
