# Generated by Django 4.0.8 on 2022-11-26 07:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0065_order_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0003_alter_managerrentinhandinventory_rnh_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=512)),
                ('type', models.PositiveIntegerField(choices=[(0, 'Физическое лицо'), (1, 'Юридическое лицо')], default=0)),
                ('birth_date', models.DateField()),
                ('attraction_method', models.CharField(choices=[('instagram', 'instagram'), ('telegram', 'telegram'), ('facebook', 'facebook'), ('google', 'google'), ('other', 'other')], max_length=255)),
                ('comment', models.TimeField(max_length=512)),
                ('avatar', models.ImageField(null=True, upload_to='')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientPassportIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('iin', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)])),
                ('document_number', models.CharField(max_length=255)),
                ('issue', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('issue_date_end', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientPassportLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('iin', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)])),
                ('address', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('contacts', models.TextField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(default='#000', max_length=9, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('comment', models.TextField(max_length=512, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('unique_id', models.CharField(max_length=32)),
                ('buy_price', models.PositiveIntegerField(null=True)),
                ('buy_date', models.DateTimeField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventories', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField(max_length=512, null=True)),
                ('disable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('type', models.PositiveIntegerField(choices=[(0, 'В Процентах'), (1, 'В Цене')])),
                ('increase_price', models.PositiveIntegerField(null=True)),
                ('decrease_price', models.PositiveIntegerField(null=True)),
                ('increase_price_percentage', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99)])),
                ('decrease_price_percentage', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('photo', models.ImageField(upload_to='inventory')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='manager.inventory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.inventorystatus'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='tarif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.inventorytarif'),
        ),
        migrations.CreateModel(
            name='ClientDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('discount_percent', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99)])),
                ('discount_amount', models.PositiveIntegerField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='manager.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='passport_individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.clientpassportindividual'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_legal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.clientpassportlegal'),
        ),
        migrations.AddField(
            model_name='client',
            name='ticks',
            field=models.ManyToManyField(to='manager.clienttick'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('unique_id', 'product')},
        ),
    ]
