# Generated by Django 4.0.8 on 2022-12-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_rename_iin_clientpassportlegal_bin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interchangeable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=255)),
                ('inventories', models.ManyToManyField(related_name='product_parts', to='manager.inventory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='inventorytarif',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ProductPart',
        ),
    ]
