# Generated by Django 4.0.8 on 2022-11-26 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_inventory_buy_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='passport_individual',
        ),
        migrations.RemoveField(
            model_name='client',
            name='passport_legal',
        ),
        migrations.AddField(
            model_name='clientpassportindividual',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_passports', to='manager.client'),
        ),
        migrations.AddField(
            model_name='clientpassportlegal',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_passports', to='manager.client'),
        ),
    ]
