# Generated by Django 4.0.8 on 2022-12-21 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_parts'),
        ('manager', '0005_interchangeable_alter_inventorytarif_default_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventorytarif',
            unique_together={('default', 'inventory', 'price', 'product_set')},
        ),
    ]
