# Generated by Django 4.0.8 on 2022-11-26 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_remove_client_passport_individual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpassportindividual',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_passports', to='manager.client'),
        ),
        migrations.AlterField(
            model_name='clientpassportlegal',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_passports', to='manager.client'),
        ),
    ]
