# Generated by Django 4.0.8 on 2022-12-21 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_inventorytarif_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='individual_passport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.clientpassportindividual'),
        ),
        migrations.AlterField(
            model_name='client',
            name='legal_passport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.clientpassportlegal'),
        ),
    ]
