# Generated by Django 4.0.8 on 2022-11-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_clientpassportindividual_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='ticks',
            new_name='tick',
        ),
    ]
