# Generated by Django 4.0.8 on 2022-11-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_rename_ticks_client_tick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='tick',
            field=models.ManyToManyField(null=True, to='manager.clienttick'),
        ),
    ]
