# Generated by Django 4.0.8 on 2022-12-22 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_client_individual_passport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventorySetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('count', models.PositiveSmallIntegerField()),
                ('interchangeable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.interchangeable')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.inventoryset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
