# Generated by Django 4.0.8 on 2022-12-23 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_inventoryset_inventorysetitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='clientdiscount',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='clientpassportindividual',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='clientpassportlegal',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='clienttick',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='interchangeable',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='inventorycategory',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='inventoryphoto',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='inventoryschedule',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='inventorysetitem',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='inventorystatus',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='inventorytarif',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='managerorder',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='rentalpoint',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='inventorysetitem',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='manager.inventoryset'),
        ),
    ]
