# Generated by Django 4.0.8 on 2022-12-23 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_client_options_alter_clientdiscount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryset',
            options={'ordering': ('-created_at',)},
        ),
    ]
