# Generated by Django 4.0.8 on 2022-12-23 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_parts'),
        ('manager', '0011_alter_inventoryset_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Запрос'), (1, 'Зарезервировано'), (2, 'В аренде'), (3, 'Отменено'), (4, 'Завершено')], default=0)),
                ('rent_start', models.DateTimeField()),
                ('rent_end', models.DateTimeField()),
                ('rent_fact_start', models.DateTimeField(null=True)),
                ('rent_fact_end', models.DateTimeField(null=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('price_discount', models.PositiveIntegerField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.client')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderRequestService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('price', models.PositiveIntegerField(null=True)),
                ('price_discount', models.FloatField(null=True)),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productdiscount')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.orderrequest')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.service')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderRequestInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('price', models.PositiveIntegerField(null=True)),
                ('price_discount', models.FloatField(null=True)),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productdiscount')),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.inventory')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.orderrequest')),
                ('tarif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.inventorytarif')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
