# Generated by Django 4.0.8 on 2022-12-30 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_orderrequest_orderrequestservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryset',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.inventorycategory'),
        ),
        migrations.AddField(
            model_name='inventoryset',
            name='unique_id',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventorysetitem',
            name='tarif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.inventorytarif'),
        ),
    ]
