# Generated by Django 4.0.8 on 2022-12-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_inventoryset_category_inventoryset_unique_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorysetitem',
            name='tarif',
        ),
        migrations.AddField(
            model_name='inventorysetitem',
            name='tarif',
            field=models.ManyToManyField(to='manager.inventorytarif'),
        ),
    ]
