# Generated by Django 4.0.8 on 2022-12-30 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_remove_inventorysetitem_tarif_inventorysetitem_tarif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorysetitem',
            old_name='tarif',
            new_name='tarifs',
        ),
    ]
