# Generated by Django 4.0.8 on 2022-12-30 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_rename_tarif_inventorysetitem_tarifs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorysetitem',
            name='tarifs',
        ),
        migrations.AddField(
            model_name='inventorytarif',
            name='interchangeable',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='manager.interchangeable'),
        ),
    ]
