# Generated by Django 4.0.8 on 2022-12-30 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_remove_inventorysetitem_tarifs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytarif',
            name='interchangeable',
        ),
        migrations.AddField(
            model_name='inventorytarif',
            name='inventory_set',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='manager.inventorysetitem'),
        ),
    ]
