# Generated by Django 4.0.8 on 2022-12-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_remove_inventorytarif_interchangeable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysetitem',
            name='tarif_price',
            field=models.IntegerField(null=True),
        ),
    ]
