# Generated by Django 4.0.8 on 2023-01-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_alter_inventoryset_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='clientpassportindividual',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='inventorysetitem',
            name='tarif_price',
            field=models.IntegerField(),
        ),
    ]
