# Generated by Django 4.0.8 on 2023-01-05 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_alter_inventoryset_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryset',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.inventorycategory'),
        ),
        migrations.AlterField(
            model_name='inventoryset',
            name='unique_id',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
