# Generated by Django 4.0.8 on 2023-01-11 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_orderrequestinventory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequestinventory',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='manager.orderrequest'),
        ),
    ]
